[build]
  command = "npm run build"
  publish = "build/"

[context.production.environment]
  VITE_DEBUG = 'false'
  VITE_DOMAIN = 'https://asp-chef-alpha.netlify.app'
  VITE_PURIFY_LOG_ERRORS = 'false'
