[build]
  command = "npm run build"
  publish = "build/"

[context.production.environment]
  VITE_DOMAIN = 'https://dumbo.alviano.net'
  VITE_PURIFY_LOG_ERRORS = 'false'

[functions]
  node_bundler = "esbuild"
